version: "3.8"

networks:
  gateway:
  backend:

services:
  gateway:
    image: soccerscore-gateway
    restart: unless-stopped
    environment:
      API_HOST: "api"
      FRONTEND_HOST: "frontend"
      FRONTEND_PORT: "3000"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - gateway

  api:
    image: soccerscore-api
    restart: unless-stopped
    environment:
      DB_HOST: "mysql"
      DB_DATABASE: "soccer-score"
      DB_USERNAME: "soccer-score"
    networks:
      - gateway
      - backend

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "soccer-score"
      MYSQL_USER: "soccer-score"
    ports:
      - "3306:3306"
    networks:
      - backend